apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: "{{ .Release.namespace }}"
spec:
  acme:
    server: "{{ .Values.letsencrypt.server }}"
    email: "{{ .Values.letsencrypt.email }}"
    privateKeySecretRef:
      name: letsencrypt-pkey
    http01: {}
